[build]
  functions = "netlify/functions"
  command = "npm run build"

[functions]
  node_bundler = "esbuild"

# Manual trigger untuk RSS processor
# Gunakan GitHub Actions atau manual trigger untuk menjalankan 2x sehari

# Environment variables are set in Netlify Dashboard
# DO NOT hardcode sensitive values here
# Go to: Site Settings > Environment Variables
#
# Required variables:
# - VITE_SUPABASE_URL
# - VITE_SUPABASE_ANON_KEY  
# - SUPABASE_SERVICE_ROLE_KEY
