[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# Netlify Scheduled Function - Auto-update RSS 2x sehari
[functions."rss-scheduler"]
  schedule = "0 6,18 * * *"  # 06:00 dan 18:00 UTC (13:00 dan 01:00 WIB)

# SPA routing: send all paths to index.html to avoid 404 on refresh
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables diperlukan di Netlify Dashboard:
# - VITE_SUPABASE_URL
# - VITE_SUPABASE_ANON_KEY  
# - SUPABASE_SERVICE_ROLE_KEY
